apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: h8etwyn0n-nodejs 
  janus-idp.io/tekton: h8etwyn0n-nodejs
  backstage.io/kubernetes-id: h8etwyn0n-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h8etwyn0n-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml